import { defineConfig } from 'tsup';
export default defineConfig({
  entry: [
    'src/index.ts',
    'src/server.ts',
    'src/config.ts',
    'src/types.ts',
    'src/scheduler.ts',
    'src/tools/store.ts',
    'src/tools/search.ts',
    'src/tools/recall.ts',
    'src/tools/forget.ts',
    'src/tools/consolidate.ts',
    'src/tools/stats.ts',
    'src/tools/admin.ts',
    'src/tools/backfill.ts',
    'src/tools/graph.ts',
    'src/graph/entity-name-dedup.ts',
    'src/tools/wiki.ts',
    'src/registration/wiki.ts',
    'src/storage/database.ts',
    'src/storage/migrations.ts',
    'src/storage/schema.ts',
    'src/embeddings/factory.ts',
    'src/rerank/factory.ts',
    'src/rerank/types.ts',
    'src/embeddings/types.ts',
    'src/governance/namespace.ts',
    'src/vectors/sqlite-vec.ts',
    'src/observability/logger.ts',
    'src/observability/metrics.ts',
    'src/cognitive/claims.ts',
    'src/cognitive/contradiction.ts',
    'src/transport/events.ts',
    'src/transport/http.ts',
    'src/transport/mcp-http-daemon.ts',
    'src/daemon.ts',
    'src/resources/index.ts',
    'src/prompts/index.ts',
  ],
  format: ['esm'],
  target: 'node18',
  outDir: 'dist',
  clean: true,
  dts: true,
  sourcemap: true,
  external: ['better-sqlite3', 'onnxruntime-node', 'sqlite-vec'],
});
