/**
 * generate-tools-doc — emit docs/TOOLS.md from the real tool registrations.
 *
 * The README historically drifted (42 vs 40+ vs 41+ while 46 tools were
 * registered) because tool docs were hand-maintained. This script feeds a
 * fake server object into the actual `register*Tools` functions, so the
 * generated document is exactly what an MCP client sees — same names,
 * same descriptions, same input schemas. Run via:
 *
 *   npx tsx scripts/generate-tools-doc.ts          # writes docs/TOOLS.md
 *   npx tsx scripts/generate-tools-doc.ts --check  # CI: fail when stale
 */
import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ZodType } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { ServerDeps } from '../src/server.js';
import { registerCoreTools } from '../src/registration/core.js';
import { registerGraphTools } from '../src/registration/graph.js';
import { registerEpisodeTools } from '../src/registration/episodes.js';
import { registerAgentTools } from '../src/registration/agents.js';
import { registerVerbatimTools } from '../src/registration/verbatim.js';
import { registerWikiTools } from '../src/registration/wiki.js';
import { registerAttributionTools, registerReflectionTool } from '../src/registration/attribution.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'docs', 'TOOLS.md');

interface ParamDoc {
  readonly name: string;
  readonly type: string;
  readonly optional: boolean;
  readonly description: string;
}

interface ToolDoc {
  readonly name: string;
  readonly description: string;
  readonly params: readonly ParamDoc[];
}

interface CategoryDoc {
  readonly title: string;
  readonly tools: ToolDoc[];
}

// Registration only destructures { config, logger } at call time; handlers
// (which need the real db/embedder) are captured but never invoked here.
const stubDeps = {
  config: { wikiDir: '~/.neuromcp/wiki' },
  logger: { debug() {}, info() {}, warn() {}, error() {} },
  db: null,
  vecStore: null,
  embedder: null,
  metrics: null,
  reranker: null,
} as unknown as ServerDeps;

function zodTypeName(schema: ZodType): string {
  // Zod v3 keeps the discriminator in _def.typeName (e.g. "ZodString").
  const def = (schema as unknown as { _def: { typeName?: string; innerType?: ZodType } })._def;
  const raw = def.typeName ?? 'unknown';
  switch (raw) {
    case 'ZodString': return 'string';
    case 'ZodNumber': return 'number';
    case 'ZodBoolean': return 'boolean';
    case 'ZodArray': return 'array';
    case 'ZodObject': return 'object';
    case 'ZodEnum': return 'enum';
    case 'ZodRecord': return 'record';
    case 'ZodUnion': return 'union';
    case 'ZodLiteral': return 'literal';
    case 'ZodOptional':
    case 'ZodDefault':
    case 'ZodNullable':
      return def.innerType !== undefined ? zodTypeName(def.innerType) : raw;
    default: return raw.replace(/^Zod/, '').toLowerCase();
  }
}

function describeParams(inputSchema: Record<string, ZodType> | undefined): ParamDoc[] {
  if (inputSchema === undefined) return [];
  return Object.entries(inputSchema).map(([name, schema]) => ({
    name,
    type: zodTypeName(schema),
    optional: schema.isOptional(),
    description: (schema as unknown as { description?: string }).description ?? '',
  }));
}

function collect(title: string, register: (server: McpServer, deps: ServerDeps) => void): CategoryDoc {
  const tools: ToolDoc[] = [];
  const fakeServer = {
    registerTool(
      name: string,
      meta: { description?: string; inputSchema?: Record<string, ZodType> },
      _handler: unknown,
    ): void {
      tools.push({
        name,
        description: meta.description ?? '',
        params: describeParams(meta.inputSchema),
      });
    },
  } as unknown as McpServer;
  register(fakeServer, stubDeps);
  return { title, tools };
}

const categories: CategoryDoc[] = [
  collect('Core memory', registerCoreTools),
  collect('Knowledge graph', registerGraphTools),
  collect('Episodes', registerEpisodeTools),
  collect('Multi-agent', registerAgentTools),
  collect('Verbatim store', registerVerbatimTools),
  collect('Wiki', registerWikiTools),
  collect('Attribution & usefulness', registerAttributionTools),
  collect('Reflection', registerReflectionTool),
];

const total = categories.reduce((n, c) => n + c.tools.length, 0);

const lines: string[] = [];
lines.push('# neuromcp MCP tools');
lines.push('');
lines.push('<!-- AUTO-GENERATED by scripts/generate-tools-doc.ts — do not edit by hand.');
lines.push('     Regenerate with: npx tsx scripts/generate-tools-doc.ts -->');
lines.push('');
lines.push(`neuromcp registers **${total} tools**. This document is generated from the`);
lines.push('actual registrations, so names, descriptions and parameters are exactly');
lines.push('what an MCP client sees.');
lines.push('');
lines.push('## Index');
lines.push('');
for (const cat of categories) {
  lines.push(`- **${cat.title}** (${cat.tools.length}): ${cat.tools.map((t) => `\`${t.name}\``).join(', ')}`);
}
lines.push('');
for (const cat of categories) {
  lines.push(`## ${cat.title}`);
  lines.push('');
  for (const tool of cat.tools) {
    lines.push(`### \`${tool.name}\``);
    lines.push('');
    lines.push(tool.description.trim());
    lines.push('');
    if (tool.params.length > 0) {
      lines.push('| Parameter | Type | Required | Description |');
      lines.push('|-----------|------|----------|-------------|');
      for (const p of tool.params) {
        const desc = p.description.replace(/\|/g, '\\|').replace(/\n/g, ' ');
        lines.push(`| \`${p.name}\` | ${p.type} | ${p.optional ? 'no' : 'yes'} | ${desc} |`);
      }
      lines.push('');
    } else {
      lines.push('_No parameters._');
      lines.push('');
    }
  }
}
const output = `${lines.join('\n').trimEnd()}\n`;

if (process.argv.includes('--check')) {
  const current = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, 'utf8') : '';
  if (current !== output) {
    process.stderr.write('docs/TOOLS.md is stale — run: npx tsx scripts/generate-tools-doc.ts\n');
    process.exit(1);
  }
  process.stdout.write(`docs/TOOLS.md is up to date (${total} tools).\n`);
} else {
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, output);
  process.stdout.write(`Wrote docs/TOOLS.md (${total} tools across ${categories.length} categories).\n`);
}
